<?php
return [
    "login",
    "register",
    "forgotPassword",
    "securityQuestions",
    "dashboard",
    "employeeTable",
    "activitiesReportTable",
    "pcTable",
    "pcForm",
    "pcFormNew",
    "pcFormEdit",
    "userTable",
    "roleTable",
    "roleForm",
    "config",
    "bulkDataLoad",
    "inventory",
    "faultReportV",
    "faultReportTable"
];
?>
